services:
  hoarder:
    container_name: hoarder
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - ./data:/data
    #ports:
    #  - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      DISABLE_SIGNUPS: true
    networks:
      - reverse-proxynet
    labels:
      - traefik.enable=true
      - traefik.http.routers.hoarder.entrypoints=web
      - traefik.http.routers.hoarder.rule=Host(`brain.zachtaiji.com`)
      - traefik.http.services.hoarder.loadbalancer.server.port=3000
      - traefik.http.routers.hoarder.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.hoarder-secure.entrypoints=websecure
      - traefik.http.routers.hoarder-secure.rule=Host(`brain.zachtaiji.com`)
      - traefik.http.routers.hoarder-secure.tls=true
      - traefik.http.routers.hoarder-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
  chrome:
    container_name: chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - reverse-proxynet
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
    networks:
      - reverse-proxynet
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true