services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - ./databases:/databases
    external_links:
      - mysql-db
    restart: always
    ports:
      - 3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: ${DB_ROOT_PASSWORD}
      MB_DB_HOST: mysql-db
    networks:
      - reverse-proxynet
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.http.routers.metabase.entrypoints=web
      - traefik.http.routers.metabase.rule=Host(`dashboard.zachtaiji.com`)
      - traefik.http.routers.metabase.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.metabase-secure.entrypoints=websecure
      - traefik.http.routers.metabase-secure.rule=Host(`dashboard.zachtaiji.com`)
      - traefik.http.routers.metabase-secure.tls=true
      - traefik.http.routers.metabase-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true