services:
  seafile-db:
    image: mariadb:10.11
    container_name: seafile-db
    #command: ['--transaction-isolation=READ-COMMITTED', '--binlog-format=ROW', '--innodb_read_only_compressed=OFF']
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - seafile-internal
    expose:
      - 3306
  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-internal
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: seafile-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - seafile-internal
  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:11.0-latest
    container_name: seafile
    volumes:
      - ./data/seafile-data:/shared
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWD=${SEAFILE_DB_PASSWORD}
      - TIME_ZONE=America/Los_Angeles
      - SEAFILE_ADMIN_EMAIL=zach@azntaiji.com
      - SEAFILE_ADMIN_PASSWORD=$SF_ADMIN_PWD
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=files.zachtaiji.com
      - SEAFILE_SERVICE_URL=files.zachtaiji.com
      - SEAFILE_FILE_SERVER_ROOT=https://files.zachtaiji.com
    depends_on:
      - seafile-db
      - memcached
      - elasticsearch
    networks:
      - seafile-internal
      - reverse-proxynet
    labels:
      - traefik.enable=true
      - traefik.http.routers.seafile.entrypoints=web
      - traefik.http.routers.seafile.rule=Host(`files.zachtaiji.com`)
      - traefik.http.routers.seafile.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.seafile-secure.entrypoints=websecure
      - traefik.http.routers.seafile-secure.rule=Host(`files.zachtaiji.com`)
      - traefik.http.routers.seafile-secure.tls=true
      - traefik.http.routers.seafile-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
  sdoc-server:
    image: seafileltd/sdoc-server:latest
    container_name: sdoc-server
    ports:
      #- 80:80
      # - 443:443
      - 7070:7070
      - 8888:8888
    volumes:
      - ./data/seadoc-data/:/shared
    environment:
      - DB_HOST=seafile-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWD=${SEAFILE_DB_PASSWORD}
      - DB_NAME=sdoc_db      
      - TIME_ZONE=America/Los_Angeles # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SDOC_SERVER_LETSENCRYPT=false # Whether to use https or not.
      - SDOC_SERVER_HOSTNAME=sdoc-server.zachtaiji.com # Specifies your host name if https is enabled.
      - SEAHUB_SERVICE_URL=https://files.zachtaiji.com
    labels:
      - traefik.enable=true
      - traefik.http.routers.sdoc-server.entrypoints=web
      - traefik.http.routers.sdoc-server.rule=Host(`sdoc-server.zachtaiji.com`)
      - traefik.http.routers.sdoc-server.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.sdoc-server-secure.entrypoints=websecure
      - traefik.http.routers.sdoc-server-secure.rule=Host(`sdoc-server.zachtaiji.com`)
      - traefik.http.routers.sdoc-server-secure.tls=true
      - traefik.http.routers.sdoc-server-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
    networks:
      - seafile-internal
      - reverse-proxynet
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true
  seafile-internal: