services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver
    restart: always
    container_name: onlyoffice_documentserver
    external_links:
      - postgres
    volumes:
      - ./logs:/var/log/onlyoffice
      - ./data:/var/www/onlyoffice/Data
      - ./cache:/var/lib/onlyoffice
      - /docker/postgres/data:/var/lib/postgresql
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=teable
      - DB_USER=teable
      - DB_PWD=${DB_PWD}
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    ports:
      - '80'
      - '443'
    labels:
      - traefik.enable=true
      - traefik.http.routers.onlyoffice.entrypoints=web
      - traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.zachtaiji.com`)
      - traefik.http.services.onlyoffice.loadbalancer.server.port=80
      - traefik.http.routers.onlyoffice.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.onlyoffice-secure.entrypoints=websecure
      - traefik.http.routers.onlyoffice-secure.rule=Host(`onlyoffice.zachtaiji.com`)
      - traefik.http.routers.onlyoffice-secure.tls=true
      - traefik.http.routers.onlyoffice-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
    networks:
      - reverse-proxynet

networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true