services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - passwords.env
    #environment:
    #  PUID: 1000 -- optional, your user id
    #  PGID: 1000 -- optional, your group id
    ports:
      - 3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - ./icons:/app/public/icons
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=web
      - traefik.http.routers.homepage.rule=Host(`home.zachtaiji.com`)
      #- traefik.http.services.homepage.loadbalancer.server.port=80
      - traefik.http.routers.homepage.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.homepage-secure.entrypoints=websecure
      - traefik.http.routers.homepage-secure.rule=Host(`home.zachtaiji.com`)
      - traefik.http.routers.homepage-secure.tls=true
      - traefik.http.routers.homepage-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
    networks:
      - reverse-proxynet

networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true