services:
  dillinger:
    build: .
    container_name: dillinger
    image: lscr.io/linuxserver/dillinger:latest
    restart: always
    volumes:
      - ./data/views:/app/dillinger/views 
      - ./data/public/css:/app/dillinger/public/css
      - ./data/public/img/icons:/app/dillinger/public/img/icons
      - ./data/config:/config
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=./pdf-export.json
    environment:
      - UID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.http.routers.dillinger.entrypoints=websecure
      - traefik.http.routers.dillinger.rule=Host(`markdown.zachtaiji.com`)
      - traefik.http.services.dillinger.loadbalancer.server.port=8080 
      - traefik.http.routers.dillinger.tls=true
      - traefik.http.routers.dillinger.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
    networks:
      - reverse-proxynet
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true