services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: 'unless-stopped'
    volumes:
      - ./cache:/cache:rw
      - ./config:/config:rw
      - /mnt/media-1:/media-1:rw
      - /mnt/media-2:/media-2:rw
    networks:
      - reverse-proxynet
    env_file:
      - jellyfin.env
    ports:
      - 8096
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`movies.zachtaiji.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.middlewares=https_redirect@docker"
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true