services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    networks:
      - reverse-proxynet
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma.entrypoints=web
      - traefik.http.routers.uptimekuma.rule=Host(`status.zachtaiji.com`)
      - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
      - traefik.http.routers.uptimekuma.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.uptimekuma-secure.entrypoints=websecure
      - traefik.http.routers.uptimekuma-secure.rule=Host(`status.zachtaiji.com`)
      - traefik.http.routers.uptimekuma-secure.tls=true
      - traefik.http.routers.uptimekuma-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true