---
services:
  caddy:
    ports:
      - ${UPTIMEKUMA_PORT:-6230}:${UPTIMEKUMA_PORT:-6230}

  uptime-kuma:
    image: ${UPTIMEKUMA_IMAGE:-louislam/uptime-kuma:1.23.13}
    restart: unless-stopped
    container_name: uptime-kuma
    volumes:
      - /opt/uptime-kuma:/app/data
    labels:
      caddy: ${SEATABLE_SERVER_HOSTNAME}:${UPTIMEKUMA_PORT:-6230}
      caddy.reverse_proxy: "{{upstreams 3001}}"
    networks:
      - frontend-net

networks:
  frontend-net:
    name: frontend-net
