services:
  minecraft-server-create:
    image: itzg/minecraft-server:latest
    container_name: "minecraft-server-create"
    #user: 1000:1000
    environment:
      TZ: "America/Los_Angeles"
      UID: 1000
      GID: 1000
      EULA: "TRUE"
      VERSION: "1.18.2"
      LEVEL: "Create Astral"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/create-astral"
      CF_API_KEY: "$$2a$$10$$OGc33tmp03F0f9kkgXYazOXfA1PCOYmFWGfMSMHHdDrC.TrRMTUrW"
      MOTD: "Create Astral Minecraft Server"
      SERVER_PORT: 25566
      USE_AIKAR_FLAGS: "true"
      MEMORY: "6144M"
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
      #JVM_DD_OPTS: "using.aikars.flags=https://mcflags.emc.gs,aikars.new.flags=true"
      EXTRA_ARGS: "--nogui"
    volumes:
      - ./data:/data:rw
    ports:
      - "25566:25566"
    stdin_open: true
    tty: true
    labels:
        - traefik.enable=true
        - traefik.http.routers.minecraft3.entrypoints=mc4
        - traefik.http.routers.minecraft3.rule=Host(`mc2.zachtaiji.com`)
        - traefik.http.services.minecraft3.loadbalancer.server.port=25566
        - traefik.http.routers.minecraft3.middlewares=non_www@docker
        - traefik.http.routers.minecraft3-secure.tls=true
        - traefik.http.routers.minecraft3-secure.tls.certresolver=myresolver
        - traefik.docker.network=reverse-proxynet
    networks:
      - reverse-proxynet
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true