---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Networking:
        - Traefik:
            icon: traefik.svg
            href: https://traefik.zachtaiji.com/dashboard/#/
            description: Reverse proxy server
            server: my-docker
            container: proxy
            widget:
                type: traefik
                url: https://traefik.zachtaiji.com
        - Tailscale:
            icon: tailscale
            href: https://login.tailscale.com/admin/machines
            description: Mesh VPN
        - CloudFlare:
            href: https://dash.cloudflare.com/
            icon: cloudflare.svg
            description: Domain and DNS management
        - Cockpit:
            href: https://zachtaiji.com:9090/system
            icon: ubuntu
            description: Remote Server Admin
        - Router:
            href: http://192.168.1.1
            icon: router
            description: Router Login
        - SpeedTest:
            abbr: ST
            href: https://www.speedtest.net/
            icon: si-speedtest-#ffffff
            description: Test internet speed
        - Mailgun:
            href: https://app.mailgun.com/dashboard
            icon: si-mailgun
            description: SMTP and API email sending service
        - Mailersend:
            href: https://app.mailersend.com/dashboard
            icon: mdi-email-arrow-right
            description: Backup SMTP and API email sending service
- Data Science & Analytics:
        - Seatable:
            icon: /icons/seatable.png
            href: https://seatable.zachtaiji.com
            description: No-code db
            server: my-docker
            container: seatable-server
        - Nocodb:
            icon: /icons/nocodb.svg
            href: https://nocodb.zachtaiji.com
            description: No-code db
            server: my-docker
            container: nocodb
        - Teable:
            icon: /icons/teable.svg
            href: https://teable.zachtaiji.com
            description: Postgres no-code db
            server: my-docker
            container: teable
        - Metabase:
            icon: metabase
            href: https://dashboard.zachtaiji.com
            description: Data viz
            server: my-docker
            container: metabase
        - Google Analytics:
            href: https://analytics.google.com/analytics/web/#/p318505188/reports/explorer?params=_u.dateOption%3Dlast90Days%26_u..nav%3Dmaui&r=4656462980&collectionId=life-cycle
            icon: google-analytics
            description: Google Analytics Dashboard
- Storage:
        - Seafile:
            icon: seafile.svg
            href: https://files.zachtaiji.com
            description: Cloud storage
            server: my-docker
            container: seafile
        - Backblaze:
            icon: backblaze.svg
            href: https://secure.backblaze.com/b2_buckets.htm
            description: Backblaze b2 bucket storage backup
- Arr Stack:
        - Jellyfin:
            icon: jellyfin.svg
            href: https://movies.zachtaiji.com
            description: Movies & TV
            server: my-docker
            container: jellyfin
            widget:
                type: jellyfin
                url: https://movies.zachtaiji.com
                key: {{HOMEPAGE_VAR_JELLYFINKEY}}
                enableBlocks: true # optional, defaults to false
                enableNowPlaying: true # optional, defaults to true
                enableUser: true # optional, defaults to false
                showEpisodeNumber: true # optional, defaults to false
                expandOneStreamToTwoRows: false # optional, defaults to true
        - Jellyseer:
            icon: jellyseerr
            href: https://jellyseerr.zachtaiji.com/
            description: Request movies & TV shows
            server: my-docker
            container: jellyseerr
        - Radarr:
            icon: radarr
            href: https://radarr.zachtaiji.com/
            description: Movie organizer/manager
            server: my-docker
            container: radarr  
            widget:
                type: radarr
                url: https://radarr.zachtaiji.com/
                key: {{HOMEPAGE_VAR_RADARRKEY}}
                enableQueue: true           
        - Sonarr:
            icon: sonarr
            href: https://sonarr.zachtaiji.com/
            description: TV show organizer/manager
            server: my-docker
            container: sonarr   
            widget:
                type: sonarr
                url: https://sonarr.zachtaiji.com/
                key: {{HOMEPAGE_VAR_SONARRKEY}}
                enableQueue: true    
        - Jackett:
            icon: jackett
            href: https://jackett.zachtaiji.com/UI/Dashboard
            description: Proxy server for torrents
            server: my-docker
            container: jackett  
            widget:
                type: jackett
                url: https://jackett.zachtaiji.com
                password: {{HOMEPAGE_VAR_JACKETTPW}}
        - Transmission:
            icon: transmission
            href: https://transmission.zachtaiji.com
            description: Torrent client
            server: my-docker
            container: transmission
            widget:
                type: transmission
                url: https://transmission.zachtaiji.com
                username: azntaiji
                password: {{HOMEPAGE_VAR_TRANSMISSIONPW}}
                rpcUrl: /transmission/ # Optional. Matches the value of "rpc-url" in your Transmission's settings.json file
- Minecraft Servers:
        - Geyser Minecraft Server:
            icon: minecraft.svg
            href: https://mc.zachtaiji.com:19132
            description: For bedrock crossplatform play
            server: my-docker
            container: minecraft-server
            widget:
                type: minecraft
                url: https://mc.zachtaiji.com
        - Fabric Minecraft Server:
            icon: minecraft.svg
            href: https://mc2.zachtaiji.com:25566
            description: Fabric Java server
            server: my-docker
            container: minecraft-server-fabric
            widget:
                type: minecraft
                url: https://mc2.zachtaiji.com:25566
- Other Apps:
        - VaultWarden:
            icon: si-vaultwarden-#ffffff
            href: https://vaultwarden.zachtaiji.com
            description: Password manager
            server: my-docker
            container: vaultwarden
        - Dillinger:
            icon: dillinger
            href: https://markdown.zachtaiji.com
            description: Markdown viewer & editor
            server: my-docker
            container: dillinger
        - n8n:
            icon: n8n.svg
            href: https://n8n.zachtaiji.com
            description: Automations
            server: my-docker
            container: n8n
- Websites & Databases:
        - Blog:
            icon: si-ghost
            href: https://zachtaiji.com
            description: Zach Taiji blog
            server: my-docker
            container: zachtaiji-com-blog
        - Static:
            icon: si-filedotio
            href: https://static.zachtaiji.com/
            description: Static fileserver
            server: my-docker
            container: static
        - Mariadb:
            icon: mariadb.svg
            server: my-docker
            container: mariadb
        - Mysql:
            icon: mysql.svg
            server: my-docker
            container: mysql-db