---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Zach's Homelab

background:
  image: https://images.unsplash.com/photo-1527348857765-589fb3b5d6f6
  opacity: 30

cardBlur: sm

theme: dark

color: gray

useEqualHeights: true

headerStyle: clean

base: https://home.zachtaiji.com

statusStyle: "dot"

quicklaunch:
  searchDescriptions: true
  showSearchSuggestions: true
  provider: google

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Arr Stack:
    style: row
    columns: 3
  Media:
    style: row
    columns: 3
  Other Apps:
    style: row
    columns: 4
  Data Science & Analytics:
    style: column
    columns: 2
  Networking:
    style: column
    columns: 1
  Websites & Databases:
    style: column
    columns: 1
  Lists:
    style: row
    columns: 3
  Personal Finance:
    style: column
    columns: 1
  Healthcare:
    style: column
    columns: 1
  Music:
    style: column
    columns: 1
  Reading:
    style: column
    columns: 1