---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Zach's Homelab

background:
  image: https://images.unsplash.com/photo-1527348857765-589fb3b5d6f6
  opacity: 30

cardBlur: sm

theme: dark

color: gray

useEqualHeights: true

headerStyle: underlined

base: https://home.zachtaiji.com

statusStyle: "dot"

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  #provider: google

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Bookmark Group on First Tab:
    tab: Main
  Arr Stack:
    tab: Main
    style: row
    columns: 4
  Databases:
    tab: Main
    style: row
    columns: 3
  Storage:
    tab: Main
    style: column
    columns: 1
  Data Science & Analytics:
    tab: Main
    style: column
    columns: 1
  Other Apps:
    tab: Main
    style: column
    columns: 1
  Websites:
    tab: Main
    style: column
    columns: 1
  Networking:
    tab: Main
    style: row
    columns: 3
  Minecraft Servers:
    tab: Minecraft
    style: row
    columns: 1
  Lists:
    tab: Bookmarks
    style: row
    columns: 1
  Personal Finance:
    tab: Bookmarks
    style: row
    columns: 1
  Healthcare:
    tab: Bookmarks
    style: row
    columns: 1
  Music:
    tab: Bookmarks
    style: row
    columns: 1
  Reading:
    tab: Bookmarks
    style: row
    columns: 1