---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- logo:
    icon: /icons/SteelheadDesign-Logo-Inverse@2x.png

- resources:
    uptime: true
    cpu: true
    memory: true

- search:
    provider: google
    target: _blank
    showSearchSuggestions: true

- openmeteo:
    label: Seattle # optional
    latitude: 47.6061
    longitude: -122.3328
    timezone: America/Los_Angeles # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1