services: 
  nocodb: 
    container_name: nocodb
    environment: 
      NC_DB: "pg://postgres:5432?u=${DATABASE_USER}&p=${DATABASE_PW}&d=${DATABASE_NAME}"
      NC_PUBLIC_URL: "https://nocodb.zachtaiji.com"
      NC_ALLOW_LOCAL_EXTERNAL_DBS: "true"
      NC_ALLOW_LOCAL_HOOKS: "true"
    image: "nocodb/nocodb:latest"
    labels: 
      - traefik.enable=true
      - traefik.http.routers.nocodb.entrypoints=web
      - traefik.http.routers.nocodb.rule=Host(`nocodb.zachtaiji.com`)
      - traefik.http.services.nocodb.loadbalancer.server.port=8080
      - traefik.http.routers.nocodb.middlewares=https_redirect@docker,non_www@docker
      - traefik.http.routers.nocodb-secure.entrypoints=websecure
      - traefik.http.routers.nocodb-secure.rule=Host(`nocodb.zachtaiji.com`)
      - traefik.http.routers.nocodb-secure.tls=true
      - traefik.http.routers.nocodb-secure.tls.certresolver=myresolver
      - traefik.docker.network=reverse-proxynet
      - com.centurylinklabs.watchtower.enable=true
    networks: [reverse-proxynet, postgres]
    restart: always
    volumes: 
      - ./data:/usr/app/data
  watchtower: 
    command: "--schedule \"0 5 * * *\" --cleanup --label-enable"
    container_name: watchtower
    image: ghcr.io/nicholas-fedor/watchtower:latest
    labels: 
      - com.centurylinklabs.watchtower.enable=true
    networks: 
      - reverse-proxynet
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true
  postgres:
    name: postgres
    external: true