services:
 postgres:
    container_name: postgres
    image: postgres:15.4
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`postgres.zachtaiji.com`)"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
      - "traefik.tcp.routers.postgres.tls=true"
    networks:
#      - teable-standalone
      - reverse-proxynet
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
 teable-db-migrate:
   container_name: teable-db-migrate
   image: ghcr.io/teableio/teable-db-migrate:latest
   environment:
     - TZ=${TIMEZONE}
     - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
#   networks:
 #     - teable-standalone

networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true
#  teable-standalone:
#    name: teable-standalone-network
#    external: true